
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.16.2
 * Query Engine version: 1c57fdcd7e44b29b9313256c76699e91c3ac3c43
 */
Prisma.prismaVersion = {
  client: "6.16.2",
  engine: "1c57fdcd7e44b29b9313256c76699e91c3ac3c43"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  admin: 'admin',
  lang: 'lang',
  bruteLimit: 'bruteLimit',
  name: 'name',
  id: 'id',
  connexionToken: 'connexionToken',
  backgroundMusic: 'backgroundMusic',
  fightSpeed: 'fightSpeed',
  gold: 'gold',
  moderator: 'moderator',
  dinorpgDone: 'dinorpgDone',
  banReason: 'banReason',
  bannedAt: 'bannedAt',
  ips: 'ips',
  displayVersusPage: 'displayVersusPage',
  displayOpponentDetails: 'displayOpponentDetails',
  lastSeen: 'lastSeen',
  lastFightDate: 'lastFightDate',
  consecutiveDaysPlayed: 'consecutiveDaysPlayed',
  unlockedTitleIds: 'unlockedTitleIds',
  equippedTitleId: 'equippedTitleId',
  bonusFightsCount: 'bonusFightsCount',
  bonusFightsDate: 'bonusFightsDate'
};

exports.Prisma.RelationLoadStrategy = {
  query: 'query',
  join: 'join'
};

exports.Prisma.UserLogScalarFieldEnum = {
  id: 'id',
  date: 'date',
  userId: 'userId',
  type: 'type',
  bruteId: 'bruteId',
  gold: 'gold',
  oldName: 'oldName'
};

exports.Prisma.GoldTransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  amount: 'amount',
  source: 'source',
  sourceData: 'sourceData',
  bruteId: 'bruteId',
  createdAt: 'createdAt'
};

exports.Prisma.BruteScalarFieldEnum = {
  name: 'name',
  level: 'level',
  xp: 'xp',
  hp: 'hp',
  ranking: 'ranking',
  gender: 'gender',
  userId: 'userId',
  pupilsCount: 'pupilsCount',
  lastFight: 'lastFight',
  fightsLeft: 'fightsLeft',
  weapons: 'weapons',
  skills: 'skills',
  agilityModifier: 'agilityModifier',
  agilityStat: 'agilityStat',
  agilityValue: 'agilityValue',
  enduranceModifier: 'enduranceModifier',
  enduranceStat: 'enduranceStat',
  enduranceValue: 'enduranceValue',
  speedModifier: 'speedModifier',
  speedStat: 'speedStat',
  speedValue: 'speedValue',
  strengthModifier: 'strengthModifier',
  strengthStat: 'strengthStat',
  strengthValue: 'strengthValue',
  pets: 'pets',
  victories: 'victories',
  destinyPath: 'destinyPath',
  createdAt: 'createdAt',
  deletedAt: 'deletedAt',
  registeredForTournament: 'registeredForTournament',
  nextTournamentDate: 'nextTournamentDate',
  currentTournamentDate: 'currentTournamentDate',
  currentTournamentStepWatched: 'currentTournamentStepWatched',
  opponentsGeneratedAt: 'opponentsGeneratedAt',
  canRankUpSince: 'canRankUpSince',
  favorite: 'favorite',
  previousDestinyPath: 'previousDestinyPath',
  body: 'body',
  colors: 'colors',
  tournamentWins: 'tournamentWins',
  globalTournamentRoundWatched: 'globalTournamentRoundWatched',
  globalTournamentWatchedDate: 'globalTournamentWatchedDate',
  deletionReason: 'deletionReason',
  willBeDeletedAt: 'willBeDeletedAt',
  id: 'id',
  masterId: 'masterId',
  clanId: 'clanId',
  wantToJoinClanId: 'wantToJoinClanId',
  eventId: 'eventId',
  resets: 'resets',
  ascendedSkills: 'ascendedSkills',
  ascendedPets: 'ascendedPets',
  ascendedWeapons: 'ascendedWeapons',
  ascensions: 'ascensions',
  eventTournamentRoundWatched: 'eventTournamentRoundWatched',
  eventTournamentWatchedDate: 'eventTournamentWatchedDate',
  losses: 'losses',
  autoFightEnabled: 'autoFightEnabled',
  winStreakCurrent: 'winStreakCurrent',
  winStreakMax: 'winStreakMax',
  bonusFightsCount: 'bonusFightsCount',
  bonusFightsDate: 'bonusFightsDate'
};

exports.Prisma.UserUsedSkillScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  skill: 'skill',
  createdAt: 'createdAt'
};

exports.Prisma.BruteStartingStatsScalarFieldEnum = {
  endurance: 'endurance',
  strength: 'strength',
  agility: 'agility',
  speed: 'speed',
  bruteId: 'bruteId',
  id: 'id'
};

exports.Prisma.FightScalarFieldEnum = {
  date: 'date',
  loser: 'loser',
  winner: 'winner',
  steps: 'steps',
  fighters: 'fighters',
  tournamentStep: 'tournamentStep',
  modifiers: 'modifiers',
  background: 'background',
  id: 'id',
  brute1Id: 'brute1Id',
  brute2Id: 'brute2Id',
  tournamentId: 'tournamentId',
  clanWarId: 'clanWarId',
  favoriteCount: 'favoriteCount',
  loserId: 'loserId',
  winnerId: 'winnerId'
};

exports.Prisma.LogScalarFieldEnum = {
  date: 'date',
  type: 'type',
  level: 'level',
  xp: 'xp',
  brute: 'brute',
  gold: 'gold',
  id: 'id',
  currentBruteId: 'currentBruteId',
  fightId: 'fightId',
  template: 'template',
  destinyChoiceId: 'destinyChoiceId'
};

exports.Prisma.DestinyChoiceScalarFieldEnum = {
  path: 'path',
  type: 'type',
  skill: 'skill',
  weapon: 'weapon',
  pet: 'pet',
  stat1: 'stat1',
  stat1Value: 'stat1Value',
  stat2: 'stat2',
  stat2Value: 'stat2Value',
  id: 'id',
  bruteId: 'bruteId',
  originalPet: 'originalPet',
  originalSkill: 'originalSkill',
  originalWeapon: 'originalWeapon'
};

exports.Prisma.TournamentScalarFieldEnum = {
  date: 'date',
  type: 'type',
  rounds: 'rounds',
  specialRule: 'specialRule',
  id: 'id',
  eventId: 'eventId'
};

exports.Prisma.TournamentAchievementScalarFieldEnum = {
  date: 'date',
  achievement: 'achievement',
  achievementCount: 'achievementCount',
  id: 'id',
  bruteId: 'bruteId'
};

exports.Prisma.TournamentGoldScalarFieldEnum = {
  date: 'date',
  userId: 'userId',
  gold: 'gold',
  id: 'id',
  source: 'source'
};

exports.Prisma.TournamentXpScalarFieldEnum = {
  date: 'date',
  xp: 'xp',
  id: 'id',
  bruteId: 'bruteId'
};

exports.Prisma.AchievementScalarFieldEnum = {
  count: 'count',
  userId: 'userId',
  name: 'name',
  id: 'id',
  bruteId: 'bruteId'
};

exports.Prisma.DailyObjectiveScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  target: 'target',
  progress: 'progress',
  completed: 'completed',
  completedAt: 'completedAt',
  rewardType: 'rewardType',
  rewardValue: 'rewardValue',
  date: 'date',
  createdAt: 'createdAt',
  claimed: 'claimed',
  claimedAt: 'claimedAt'
};

exports.Prisma.WeeklyObjectiveScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  target: 'target',
  progress: 'progress',
  completed: 'completed',
  completedAt: 'completedAt',
  rewardType: 'rewardType',
  rewardValue: 'rewardValue',
  weekStart: 'weekStart',
  createdAt: 'createdAt',
  claimed: 'claimed',
  claimedAt: 'claimedAt'
};

exports.Prisma.MissionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  category: 'category',
  type: 'type',
  title: 'title',
  description: 'description',
  target: 'target',
  progress: 'progress',
  completed: 'completed',
  completedAt: 'completedAt',
  claimed: 'claimed',
  claimedAt: 'claimedAt',
  rewardType: 'rewardType',
  rewardValue: 'rewardValue',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MissionAchievementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  target: 'target',
  progress: 'progress',
  completed: 'completed',
  completedAt: 'completedAt',
  claimed: 'claimed',
  claimedAt: 'claimedAt',
  rewardType: 'rewardType',
  rewardValue: 'rewardValue',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PermanentAchievementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  level: 'level',
  target: 'target',
  progress: 'progress',
  completed: 'completed',
  completedAt: 'completedAt',
  claimed: 'claimed',
  claimedAt: 'claimedAt',
  rewardType: 'rewardType',
  rewardValue: 'rewardValue',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BruteReportScalarFieldEnum = {
  date: 'date',
  status: 'status',
  count: 'count',
  reason: 'reason',
  id: 'id',
  bruteId: 'bruteId',
  handlerId: 'handlerId',
  handledAt: 'handledAt',
  bruteName: 'bruteName'
};

exports.Prisma.ServerStateScalarFieldEnum = {
  globalTournamentValid: 'globalTournamentValid',
  activeModifiers: 'activeModifiers',
  modifiersEndAt: 'modifiersEndAt',
  id: 'id',
  nextModifiers: 'nextModifiers'
};

exports.Prisma.BannedWordScalarFieldEnum = {
  word: 'word',
  id: 'id'
};

exports.Prisma.BannedIpScalarFieldEnum = {
  id: 'id'
};

exports.Prisma.ClanScalarFieldEnum = {
  name: 'name',
  limit: 'limit',
  points: 'points',
  boss: 'boss',
  damageOnBoss: 'damageOnBoss',
  bossRotationDate: 'bossRotationDate',
  id: 'id',
  masterId: 'masterId',
  elo: 'elo',
  participateInClanWar: 'participateInClanWar',
  deletedAt: 'deletedAt'
};

exports.Prisma.ClanThreadScalarFieldEnum = {
  title: 'title',
  locked: 'locked',
  postCount: 'postCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  pinned: 'pinned',
  id: 'id',
  clanId: 'clanId',
  creatorId: 'creatorId'
};

exports.Prisma.ClanPostScalarFieldEnum = {
  date: 'date',
  message: 'message',
  id: 'id',
  threadId: 'threadId',
  authorId: 'authorId'
};

exports.Prisma.BossDamageScalarFieldEnum = {
  damage: 'damage',
  clanId: 'clanId',
  bruteId: 'bruteId',
  id: 'id'
};

exports.Prisma.ClanWarScalarFieldEnum = {
  id: 'id',
  duration: 'duration',
  date: 'date',
  status: 'status',
  attackerId: 'attackerId',
  defenderId: 'defenderId',
  winnerId: 'winnerId',
  type: 'type',
  attackerEloChange: 'attackerEloChange',
  defenderEloChange: 'defenderEloChange',
  attackerWins: 'attackerWins',
  defenderWins: 'defenderWins'
};

exports.Prisma.ClanWarFightersScalarFieldEnum = {
  id: 'id',
  clanWarId: 'clanWarId',
  day: 'day'
};

exports.Prisma.InventoryItemScalarFieldEnum = {
  type: 'type',
  count: 'count',
  id: 'id',
  bruteId: 'bruteId',
  userId: 'userId'
};

exports.Prisma.BattlePassSeasonScalarFieldEnum = {
  id: 'id',
  name: 'name',
  startDate: 'startDate',
  endDate: 'endDate'
};

exports.Prisma.BattlePassRewardScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  level: 'level',
  rewardType: 'rewardType',
  valueInt: 'valueInt',
  valueString: 'valueString'
};

exports.Prisma.BattlePassMissionScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  type: 'type',
  target: 'target',
  xpReward: 'xpReward',
  difficulty: 'difficulty'
};

exports.Prisma.UserBattlePassProgressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  seasonId: 'seasonId',
  totalXp: 'totalXp',
  claimedLevels: 'claimedLevels'
};

exports.Prisma.UserBattlePassMissionProgressScalarFieldEnum = {
  userId: 'userId',
  missionId: 'missionId',
  progress: 'progress',
  completedAt: 'completedAt'
};

exports.Prisma.BruteTemporaryEffectScalarFieldEnum = {
  id: 'id',
  bruteId: 'bruteId',
  skillName: 'skillName',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.BruteTemporaryWeaponScalarFieldEnum = {
  id: 'id',
  bruteId: 'bruteId',
  weaponName: 'weaponName',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.CosmeticPresetScalarFieldEnum = {
  id: 'id',
  name: 'name',
  body: 'body',
  colors: 'colors'
};

exports.Prisma.UserUnlockedCosmeticScalarFieldEnum = {
  userId: 'userId',
  cosmeticPresetId: 'cosmeticPresetId'
};

exports.Prisma.ShopItemScalarFieldEnum = {
  id: 'id',
  type: 'type',
  name: 'name',
  description: 'description',
  price: 'price',
  valueInt: 'valueInt',
  valueString: 'valueString',
  available: 'available',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReleaseScalarFieldEnum = {
  version: 'version',
  date: 'date'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  date: 'date',
  type: 'type',
  winnerId: 'winnerId',
  status: 'status',
  maxLevel: 'maxLevel',
  finishedAt: 'finishedAt',
  maxRound: 'maxRound',
  sortedBrutes: 'sortedBrutes'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  message: 'message',
  read: 'read',
  date: 'date',
  link: 'link',
  severity: 'severity'
};

exports.Prisma.ConfigScalarFieldEnum = {
  key: 'key',
  value: 'value',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.Lang = exports.$Enums.Lang = {
  en: 'en',
  fr: 'fr',
  de: 'de',
  es: 'es',
  ru: 'ru',
  pt: 'pt'
};

exports.UserLogType = exports.$Enums.UserLogType = {
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  GOLD_WIN: 'GOLD_WIN',
  CREATE_BRUTE: 'CREATE_BRUTE',
  RENAME_BRUTE: 'RENAME_BRUTE',
  SACRIFICE_BRUTE: 'SACRIFICE_BRUTE',
  BANNED: 'BANNED',
  GOLD_LOSS: 'GOLD_LOSS'
};

exports.Gender = exports.$Enums.Gender = {
  male: 'male',
  female: 'female'
};

exports.WeaponName = exports.$Enums.WeaponName = {
  fan: 'fan',
  keyboard: 'keyboard',
  knife: 'knife',
  leek: 'leek',
  mug: 'mug',
  sai: 'sai',
  racquet: 'racquet',
  axe: 'axe',
  bumps: 'bumps',
  flail: 'flail',
  fryingPan: 'fryingPan',
  hatchet: 'hatchet',
  mammothBone: 'mammothBone',
  morningStar: 'morningStar',
  trombone: 'trombone',
  baton: 'baton',
  halbard: 'halbard',
  lance: 'lance',
  trident: 'trident',
  whip: 'whip',
  noodleBowl: 'noodleBowl',
  piopio: 'piopio',
  shuriken: 'shuriken',
  broadsword: 'broadsword',
  scimitar: 'scimitar',
  sword: 'sword'
};

exports.SkillName = exports.$Enums.SkillName = {
  herculeanStrength: 'herculeanStrength',
  felineAgility: 'felineAgility',
  lightningBolt: 'lightningBolt',
  vitality: 'vitality',
  immortality: 'immortality',
  reconnaissance: 'reconnaissance',
  weaponsMaster: 'weaponsMaster',
  martialArts: 'martialArts',
  sixthSense: 'sixthSense',
  hostility: 'hostility',
  fistsOfFury: 'fistsOfFury',
  shield: 'shield',
  armor: 'armor',
  toughenedSkin: 'toughenedSkin',
  untouchable: 'untouchable',
  sabotage: 'sabotage',
  shock: 'shock',
  bodybuilder: 'bodybuilder',
  relentless: 'relentless',
  survival: 'survival',
  leadSkeleton: 'leadSkeleton',
  balletShoes: 'balletShoes',
  determination: 'determination',
  firstStrike: 'firstStrike',
  resistant: 'resistant',
  counterAttack: 'counterAttack',
  ironHead: 'ironHead',
  thief: 'thief',
  fierceBrute: 'fierceBrute',
  tragicPotion: 'tragicPotion',
  net: 'net',
  bomb: 'bomb',
  hammer: 'hammer',
  cryOfTheDamned: 'cryOfTheDamned',
  hypnosis: 'hypnosis',
  flashFlood: 'flashFlood',
  tamer: 'tamer',
  regeneration: 'regeneration',
  chef: 'chef',
  spy: 'spy',
  saboteur: 'saboteur',
  backup: 'backup',
  hideaway: 'hideaway',
  monk: 'monk',
  vampirism: 'vampirism',
  chaining: 'chaining',
  haste: 'haste',
  treat: 'treat',
  repulse: 'repulse',
  fastMetabolism: 'fastMetabolism'
};

exports.PetName = exports.$Enums.PetName = {
  dog1: 'dog1',
  dog2: 'dog2',
  dog3: 'dog3',
  panther: 'panther',
  bear: 'bear'
};

exports.DestinyChoiceSide = exports.$Enums.DestinyChoiceSide = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT'
};

exports.FightModifier = exports.$Enums.FightModifier = {
  noThrows: 'noThrows',
  focusOpponent: 'focusOpponent',
  alwaysUseSupers: 'alwaysUseSupers',
  drawEveryWeapon: 'drawEveryWeapon',
  doubleAgility: 'doubleAgility',
  randomSkill: 'randomSkill',
  randomWeapon: 'randomWeapon',
  bareHandsFirstHit: 'bareHandsFirstHit',
  startWithWeapon: 'startWithWeapon',
  chaos: 'chaos',
  doubleXP: 'doubleXP',
  doubleHP: 'doubleHP',
  noPets: 'noPets',
  allHaveBear: 'allHaveBear',
  doubleFights: 'doubleFights',
  crazyDay: 'crazyDay'
};

exports.LogType = exports.$Enums.LogType = {
  win: 'win',
  lose: 'lose',
  child: 'child',
  childup: 'childup',
  up: 'up',
  lvl: 'lvl',
  tournament: 'tournament',
  tournamentXp: 'tournamentXp',
  bossDefeat: 'bossDefeat',
  ascend: 'ascend',
  bossFight: 'bossFight'
};

exports.DestinyChoiceType = exports.$Enums.DestinyChoiceType = {
  skill: 'skill',
  weapon: 'weapon',
  pet: 'pet',
  stats: 'stats'
};

exports.BruteStat = exports.$Enums.BruteStat = {
  endurance: 'endurance',
  strength: 'strength',
  agility: 'agility',
  speed: 'speed'
};

exports.TournamentType = exports.$Enums.TournamentType = {
  DAILY: 'DAILY',
  GLOBAL: 'GLOBAL',
  CUSTOM: 'CUSTOM',
  SPECIAL: 'SPECIAL',
  BATTLE_ROYALE: 'BATTLE_ROYALE',
  UNLIMITED_GLOBAL: 'UNLIMITED_GLOBAL',
  COPA_DEL_REY_SEMIFINAL: 'COPA_DEL_REY_SEMIFINAL',
  COPA_DEL_REY: 'COPA_DEL_REY'
};

exports.AchievementName = exports.$Enums.AchievementName = {
  wins: 'wins',
  defeats: 'defeats',
  flawless: 'flawless',
  winWith1HP: 'winWith1HP',
  steal2Weapons: 'steal2Weapons',
  singleHitWin: 'singleHitWin',
  combo3: 'combo3',
  combo4: 'combo4',
  combo5: 'combo5',
  counter5: 'counter5',
  evade10: 'evade10',
  block25: 'block25',
  counter4b2b: 'counter4b2b',
  reversal4b2b: 'reversal4b2b',
  block4b2b: 'block4b2b',
  evade4b2b: 'evade4b2b',
  throw10b2b: 'throw10b2b',
  disarm4: 'disarm4',
  disarm8: 'disarm8',
  damage50once: 'damage50once',
  damage100once: 'damage100once',
  hit20times: 'hit20times',
  use10skills: 'use10skills',
  kill3pets: 'kill3pets',
  maxDamage: 'maxDamage',
  hpHealed: 'hpHealed',
  saboteur: 'saboteur',
  dog: 'dog',
  panther: 'panther',
  bear: 'bear',
  panther_bear: 'panther_bear',
  felAg_fistsOfF: 'felAg_fistsOfF',
  felAg_fistsOfF_untouch_relentless: 'felAg_fistsOfF_untouch_relentless',
  vita_armor_toughened: 'vita_armor_toughened',
  herculStr_hammer_fierceBrute: 'herculStr_hammer_fierceBrute',
  shock: 'shock',
  balletShoes_survival: 'balletShoes_survival',
  cryOfTheDamned_hypnosis: 'cryOfTheDamned_hypnosis',
  shield_counterAttack: 'shield_counterAttack',
  reconnaissance_monk: 'reconnaissance_monk',
  immortality: 'immortality',
  doubleBoost: 'doubleBoost',
  tripleBoost: 'tripleBoost',
  quadrupleBoost: 'quadrupleBoost',
  regeneration_potion: 'regeneration_potion',
  bear_tamer: 'bear_tamer',
  tripleDogs: 'tripleDogs',
  fiveWeapons: 'fiveWeapons',
  tenWeapons: 'tenWeapons',
  fifteenWeapons: 'fifteenWeapons',
  twentyWeapons: 'twentyWeapons',
  twentyThreeWeapons: 'twentyThreeWeapons',
  monk_sixthSense_whip: 'monk_sixthSense_whip',
  weaponsMaster_sharp_bodybuilder_heavy: 'weaponsMaster_sharp_bodybuilder_heavy',
  hostility_counterWeapon: 'hostility_counterWeapon',
  flashFlood_twelveWeapons: 'flashFlood_twelveWeapons',
  lightningBolt_firstStrike: 'lightningBolt_firstStrike',
  herculeanStrength: 'herculeanStrength',
  felineAgility: 'felineAgility',
  lightningBolt: 'lightningBolt',
  vitality: 'vitality',
  potion_chef: 'potion_chef',
  tamer_net: 'tamer_net',
  untouchable_balletShoes: 'untouchable_balletShoes',
  survival_resistant: 'survival_resistant',
  hideaway_spy: 'hideaway_spy',
  weaponsFast3: 'weaponsFast3',
  weaponsSharp3: 'weaponsSharp3',
  weaponsHeavy3: 'weaponsHeavy3',
  weaponsLong3: 'weaponsLong3',
  weaponsThrown3: 'weaponsThrown3',
  weaponsBlunt3: 'weaponsBlunt3',
  thor: 'thor',
  deflector: 'deflector',
  allFastWeapons: 'allFastWeapons',
  allSharpWeapons: 'allSharpWeapons',
  allHeavyWeapons: 'allHeavyWeapons',
  allLongWeapons: 'allLongWeapons',
  allThrownWeapons: 'allThrownWeapons',
  allBluntWeapons: 'allBluntWeapons',
  agility50: 'agility50',
  agility100: 'agility100',
  speed50: 'speed50',
  speed100: 'speed100',
  strength50: 'strength50',
  strength100: 'strength100',
  hp300: 'hp300',
  hp600: 'hp600',
  maxLevel: 'maxLevel',
  allAchievements: 'allAchievements',
  winTournamentAs20: 'winTournamentAs20',
  winTournamentAs15: 'winTournamentAs15',
  looseAgainst2: 'looseAgainst2',
  looseAgainst3: 'looseAgainst3',
  looseAgainst4: 'looseAgainst4',
  winAgainst2: 'winAgainst2',
  winAgainst3: 'winAgainst3',
  winAgainst4: 'winAgainst4',
  winAsLower: 'winAsLower',
  win: 'win',
  battleRoyaleWin: 'battleRoyaleWin',
  rankUp10: 'rankUp10',
  rankUp9: 'rankUp9',
  rankUp8: 'rankUp8',
  rankUp7: 'rankUp7',
  rankUp6: 'rankUp6',
  rankUp5: 'rankUp5',
  rankUp4: 'rankUp4',
  rankUp3: 'rankUp3',
  rankUp2: 'rankUp2',
  rankUp1: 'rankUp1',
  rankUp0: 'rankUp0',
  sacrifice: 'sacrifice',
  beta: 'beta',
  bug: 'bug',
  ascend: 'ascend'
};

exports.ObjectiveType = exports.$Enums.ObjectiveType = {
  WIN_FIGHTS: 'WIN_FIGHTS',
  WIN_TOURNAMENT: 'WIN_TOURNAMENT',
  WIN_SPECIAL_TOURNAMENT: 'WIN_SPECIAL_TOURNAMENT',
  LEVEL_UP: 'LEVEL_UP',
  COMPLETE_FIGHTS: 'COMPLETE_FIGHTS',
  COMPLETE_SPECIAL_FIGHTS: 'COMPLETE_SPECIAL_FIGHTS',
  USE_SKILLS: 'USE_SKILLS',
  GAIN_XP: 'GAIN_XP',
  REACH_LEVEL: 'REACH_LEVEL',
  COMPLETE_ACHIEVEMENTS: 'COMPLETE_ACHIEVEMENTS'
};

exports.ObjectiveRewardType = exports.$Enums.ObjectiveRewardType = {
  GOLD: 'GOLD',
  TITLE: 'TITLE'
};

exports.MissionCategory = exports.$Enums.MissionCategory = {
  COMBAT: 'COMBAT',
  PROGRESSION: 'PROGRESSION',
  SOCIAL: 'SOCIAL',
  EVENTS: 'EVENTS',
  SPECIAL: 'SPECIAL'
};

exports.MissionType = exports.$Enums.MissionType = {
  WIN_FIGHTS: 'WIN_FIGHTS',
  WIN_FIGHTS_STREAK: 'WIN_FIGHTS_STREAK',
  WIN_TOURNAMENT: 'WIN_TOURNAMENT',
  DEAL_DAMAGE: 'DEAL_DAMAGE',
  PARTICIPATE_CLAN_WAR: 'PARTICIPATE_CLAN_WAR',
  REACH_LEVEL: 'REACH_LEVEL',
  ASCEND: 'ASCEND',
  COMPLETE_FIGHTS: 'COMPLETE_FIGHTS',
  GAIN_XP: 'GAIN_XP',
  FOLLOW_BRUTES: 'FOLLOW_BRUTES',
  JOIN_CLAN: 'JOIN_CLAN',
  PARTICIPATE_CLAN_WARS: 'PARTICIPATE_CLAN_WARS',
  PARTICIPATE_EVENT: 'PARTICIPATE_EVENT',
  REACH_EVENT_FINAL: 'REACH_EVENT_FINAL',
  WIN_EVENT: 'WIN_EVENT',
  CREATE_BRUTES: 'CREATE_BRUTES',
  TRY_DIFFERENT_SKILLS: 'TRY_DIFFERENT_SKILLS'
};

exports.MissionRewardType = exports.$Enums.MissionRewardType = {
  GOLD: 'GOLD',
  TITLE: 'TITLE'
};

exports.MissionAchievementType = exports.$Enums.MissionAchievementType = {
  COMPLETE_COMBAT_MISSIONS: 'COMPLETE_COMBAT_MISSIONS',
  COMPLETE_PROGRESSION_MISSIONS: 'COMPLETE_PROGRESSION_MISSIONS',
  COMPLETE_SOCIAL_MISSIONS: 'COMPLETE_SOCIAL_MISSIONS',
  COMPLETE_EVENTS_MISSIONS: 'COMPLETE_EVENTS_MISSIONS',
  COMPLETE_SPECIAL_MISSIONS: 'COMPLETE_SPECIAL_MISSIONS',
  COMPLETE_DAILY_MISSIONS: 'COMPLETE_DAILY_MISSIONS',
  COMPLETE_WEEKLY_MISSIONS: 'COMPLETE_WEEKLY_MISSIONS',
  COMPLETE_ALL_MISSIONS: 'COMPLETE_ALL_MISSIONS'
};

exports.AchievementType = exports.$Enums.AchievementType = {
  WIN_FIGHTS_TOTAL: 'WIN_FIGHTS_TOTAL',
  WIN_FIGHTS_SINGLE_BRUTE: 'WIN_FIGHTS_SINGLE_BRUTE',
  WIN_TOURNAMENTS_TOTAL: 'WIN_TOURNAMENTS_TOTAL',
  WIN_TOURNAMENTS_CONSECUTIVE: 'WIN_TOURNAMENTS_CONSECUTIVE',
  REACH_LEVEL: 'REACH_LEVEL',
  REACH_LEVEL_MULTIPLE: 'REACH_LEVEL_MULTIPLE',
  COMPLETE_FIGHTS_TOTAL: 'COMPLETE_FIGHTS_TOTAL',
  COMPLETE_FIGHTS_SINGLE_BRUTE: 'COMPLETE_FIGHTS_SINGLE_BRUTE',
  GAIN_GOLD_TOTAL: 'GAIN_GOLD_TOTAL',
  GAIN_GOLD_MONTHLY: 'GAIN_GOLD_MONTHLY',
  ASCEND_TOTAL: 'ASCEND_TOTAL',
  ASCEND_SINGLE_BRUTE: 'ASCEND_SINGLE_BRUTE',
  RESET_TOTAL: 'RESET_TOTAL',
  RESET_SINGLE_BRUTE: 'RESET_SINGLE_BRUTE',
  CLAN_WARS_WON: 'CLAN_WARS_WON',
  CLAN_BOSS_CHALLENGES: 'CLAN_BOSS_CHALLENGES',
  CLAN_POINTS_CONTRIBUTED: 'CLAN_POINTS_CONTRIBUTED',
  EVENTS_PARTICIPATED: 'EVENTS_PARTICIPATED',
  EVENTS_FINAL_REACHED: 'EVENTS_FINAL_REACHED',
  EVENTS_WON: 'EVENTS_WON',
  AUTO_FIGHTS_COMPLETED: 'AUTO_FIGHTS_COMPLETED',
  DAMAGE_DEALT_TOTAL: 'DAMAGE_DEALT_TOTAL',
  WIN_STREAK: 'WIN_STREAK',
  TOP_RANKING: 'TOP_RANKING',
  BRUTES_IN_TOP_100: 'BRUTES_IN_TOP_100',
  DAYS_PLAYED_CONSECUTIVE: 'DAYS_PLAYED_CONSECUTIVE'
};

exports.AchievementLevel = exports.$Enums.AchievementLevel = {
  BRONZE: 'BRONZE',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM'
};

exports.AchievementRewardType = exports.$Enums.AchievementRewardType = {
  GOLD: 'GOLD',
  TITLE: 'TITLE',
  COSMETIC: 'COSMETIC'
};

exports.BruteReportStatus = exports.$Enums.BruteReportStatus = {
  pending: 'pending',
  accepted: 'accepted',
  rejected: 'rejected'
};

exports.BruteReportReason = exports.$Enums.BruteReportReason = {
  name: 'name'
};

exports.BossName = exports.$Enums.BossName = {
  GoldClaw: 'GoldClaw',
  EmberFang: 'EmberFang',
  Cerberus: 'Cerberus'
};

exports.ClanWarStatus = exports.$Enums.ClanWarStatus = {
  pending: 'pending',
  ongoing: 'ongoing',
  waitingForRewards: 'waitingForRewards',
  finished: 'finished'
};

exports.ClanWarType = exports.$Enums.ClanWarType = {
  friendly: 'friendly',
  official: 'official'
};

exports.InventoryItemType = exports.$Enums.InventoryItemType = {
  visualReset: 'visualReset',
  bossTicket: 'bossTicket',
  nameChange: 'nameChange',
  favoriteFight: 'favoriteFight'
};

exports.BattlePassRewardType = exports.$Enums.BattlePassRewardType = {
  GOLD: 'GOLD',
  TITLE: 'TITLE',
  COSMETIC: 'COSMETIC',
  BONUS_FIGHTS: 'BONUS_FIGHTS',
  TEMPORARY_SKILL: 'TEMPORARY_SKILL',
  TEMPORARY_WEAPON: 'TEMPORARY_WEAPON'
};

exports.BattlePassMissionType = exports.$Enums.BattlePassMissionType = {
  WIN_FIGHTS: 'WIN_FIGHTS',
  PARTICIPATE_TOURNAMENTS: 'PARTICIPATE_TOURNAMENTS',
  WIN_TOURNAMENTS: 'WIN_TOURNAMENTS',
  DEAL_DAMAGE: 'DEAL_DAMAGE',
  WIN_STREAK: 'WIN_STREAK',
  ASCEND: 'ASCEND'
};

exports.BattlePassMissionDifficulty = exports.$Enums.BattlePassMissionDifficulty = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD'
};

exports.ShopItemType = exports.$Enums.ShopItemType = {
  COSMETIC: 'COSMETIC',
  BONUS_FIGHTS: 'BONUS_FIGHTS',
  TEMPORARY_WEAPON: 'TEMPORARY_WEAPON',
  TEMPORARY_SKILL: 'TEMPORARY_SKILL'
};

exports.EventType = exports.$Enums.EventType = {
  battleRoyale: 'battleRoyale'
};

exports.EventStatus = exports.$Enums.EventStatus = {
  ongoing: 'ongoing',
  finished: 'finished',
  starting: 'starting'
};

exports.NotificationSeverity = exports.$Enums.NotificationSeverity = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  error: 'error'
};

exports.Prisma.ModelName = {
  User: 'User',
  UserLog: 'UserLog',
  GoldTransaction: 'GoldTransaction',
  Brute: 'Brute',
  UserUsedSkill: 'UserUsedSkill',
  BruteStartingStats: 'BruteStartingStats',
  Fight: 'Fight',
  Log: 'Log',
  DestinyChoice: 'DestinyChoice',
  Tournament: 'Tournament',
  TournamentAchievement: 'TournamentAchievement',
  TournamentGold: 'TournamentGold',
  TournamentXp: 'TournamentXp',
  Achievement: 'Achievement',
  DailyObjective: 'DailyObjective',
  WeeklyObjective: 'WeeklyObjective',
  Mission: 'Mission',
  MissionAchievement: 'MissionAchievement',
  PermanentAchievement: 'PermanentAchievement',
  BruteReport: 'BruteReport',
  ServerState: 'ServerState',
  BannedWord: 'BannedWord',
  BannedIp: 'BannedIp',
  Clan: 'Clan',
  ClanThread: 'ClanThread',
  ClanPost: 'ClanPost',
  BossDamage: 'BossDamage',
  ClanWar: 'ClanWar',
  ClanWarFighters: 'ClanWarFighters',
  InventoryItem: 'InventoryItem',
  BattlePassSeason: 'BattlePassSeason',
  BattlePassReward: 'BattlePassReward',
  BattlePassMission: 'BattlePassMission',
  UserBattlePassProgress: 'UserBattlePassProgress',
  UserBattlePassMissionProgress: 'UserBattlePassMissionProgress',
  BruteTemporaryEffect: 'BruteTemporaryEffect',
  BruteTemporaryWeapon: 'BruteTemporaryWeapon',
  CosmeticPreset: 'CosmeticPreset',
  UserUnlockedCosmetic: 'UserUnlockedCosmetic',
  ShopItem: 'ShopItem',
  Release: 'Release',
  Event: 'Event',
  Notification: 'Notification',
  Config: 'Config'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
